//add course constaints
export const COURSE_REG_REQUEST = 'COURSE_REG_REQUEST'
export const COURSE_REG_SUCCESS = 'COURSE_REG_SUCCESS'
export const COURSE_REG_FAIL = 'COURSE_REG_FAIL'
export const COURSE_REG_CLEAR = 'COURSE_REG_CLEAR'

//show all courses
export const COURSE_SHOW_REQUEST = 'COURSE_SHOW_REQUEST'
export const COURSE_SHOW_SUCCESS = 'COURSE_SHOW_SUCCESS'
export const COURSE_SHOW_FAIL = 'COURSE_SHOW_FAIL'


